Pathology.Web/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Security.Claims;
using Pathology.Web.Service.IService;
using Pathology.Web.Models;
using Pathology.Web.Utility;
using System.IdentityModel.Tokens.Jwt;
using Web.Service.IService;


namespace Pathology.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;
        private readonly ITokenProvider _tokenProvider;

        public AuthController(IAuthService authService, ITokenProvider tokenProvider)
        {
            _authService = authService;
            _tokenProvider = tokenProvider; 
        }

        [HttpGet]
        public IActionResult Login()
        {
            LoginRequestDto loginRequestDto = new();
            return View(loginRequestDto);
        }
        [HttpPost]
        public async Task<IActionResult> Login(LoginRequestDto obj)
        {
            ResponseDto responseDto = await _authService.LoginAsync(obj);

            if (responseDto != null && responseDto.IsSuccess)
            {
                LoginResponseDto loginResponseDto =
                    JsonConvert.DeserializeObject<LoginResponseDto>(Convert.ToString(responseDto.Result));

                await SignInUser(loginResponseDto);
                _tokenProvider.SetToken(loginResponseDto.Token);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                //TempData["error"] = responseDto.Message;
                //return View(obj);
                ModelState.AddModelError("CustomError", responseDto.Message);
                return View(obj);
            }
        }


        [HttpGet]
        public IActionResult Register()
        {
            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text=SD.RoleAdmin,Value=SD.RoleAdmin},
                new SelectListItem{Text=SD.RoleCustomer,Value=SD.RoleCustomer},
            };

            ViewBag.RoleList = roleList;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(RegisterationRequestDto obj)
        {
            ResponseDto result = await _authService.RegisterAsync(obj);
            ResponseDto assingRole;

            if (result != null && result.IsSuccess)
            {
                if (string.IsNullOrEmpty(obj.Role))
                {
                    obj.Role = SD.RoleCustomer;
                }
                assingRole = await _authService.AssignRoleAsync(obj);
                if (assingRole != null && assingRole.IsSuccess)
                {
                    TempData["success"] = "Registration Successful";
                    return RedirectToAction(nameof(Login));
                }
            }
            else
            {
                TempData["error"] = result.Message;
            }

            var roleList = new List<SelectListItem>()
            {
                new SelectListItem{Text=SD.RoleAdmin,Value=SD.RoleAdmin},
                new SelectListItem{Text=SD.RoleCustomer,Value=SD.RoleCustomer},
            };

            ViewBag.RoleList = roleList;
            return View(obj);
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            _tokenProvider.ClearToken();
            return RedirectToAction("Index", "Home");
        }
        private async Task SignInUser(LoginResponseDto model)
        {
            var handler = new JwtSecurityTokenHandler();

            var jwt = handler.ReadJwtToken(model.Token);

            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Sub).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Name).Value));


            identity.AddClaim(new Claim(ClaimTypes.Name,
                jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
            identity.AddClaim(new Claim(ClaimTypes.Role,
                jwt.Claims.FirstOrDefault(u => u.Type == "role").Value));



            var principal = new ClaimsPrincipal(identity);
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
        }
    }
}

Pathology.Web/Controllers/PatientController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Pathology.Web.Models;
using Pathology.Web.Service.IService;


namespace Pathology.Web.Controllers
{
    public class PatientController : Controller
    {
        private readonly IPatientService _patientService;

        public PatientController(IPatientService patientService)
        {
            _patientService = patientService;
        }

        public async Task<IActionResult> PatientIndex()
        {
            List<PatientDto>? list = new();

            ResponseDto? response = await _patientService.GetAllPatientAsync();

            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<PatientDto>>(Convert.ToString(response.Result));
            }

            return View(list);
        }

        public async Task<IActionResult> PatientCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PatientCreate(PatientDto model)
        {
            if (ModelState.IsValid)
            {
                ResponseDto? response = await _patientService.CreatePatientAsync(model);

                if (response != null && response.IsSuccess)
                {
                    //TempData["success"] = "Coupon created successfully";
                    return RedirectToAction(nameof(PatientIndex));
                }
                //else
                //{
                //    TempData["error"] = response?.Message;
                //}
            }
            return View(model);
        }
        public async Task<IActionResult> PatientDelete(int patientId)
        {
            ResponseDto? response = await _patientService.GetPatientByNumberAsync(patientId);

            if (response != null && response.IsSuccess)
            {
                PatientDto? model = JsonConvert.DeserializeObject<PatientDto>(Convert.ToString(response.Result));
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> PatientDelete(PatientDto patientDto)
        {
            ResponseDto? response = await _patientService.DeletePatientAsync(patientDto.PatientNumber);

            if (response != null && response.IsSuccess)
            {

                return RedirectToAction(nameof(PatientIndex));
            }

            return View(patientDto);
        }
        public async Task<IActionResult> PatientUpdate(int patientId)
        {
            ResponseDto? response = await _patientService.GetPatientByNumberAsync(patientId);

            if (response != null && response.IsSuccess)
            {
                PatientDto? model = JsonConvert.DeserializeObject<PatientDto>(Convert.ToString(response.Result));
                return View(model);
            }

            return NotFound();
        }
        
        [HttpPost]
       
        public async Task<IActionResult> UpdateVilla(PatientDto model)
        {
            //if (ModelState.IsValid)
            //{
              //  TempData["success"] = "Villa updated successfully";
                //var response = await _villaService.UpdateAsync<APIResponse>(model, HttpContext.Session.GetString(SD.SessionToken));
                //if (response != null && response.IsSuccess)
                //{
                //    return RedirectToAction(nameof(IndexVilla));
                //}
                ResponseDto? response = await _patientService.UpdatePatientAsync(model);

                if (response != null && response.IsSuccess)
                {

                    return RedirectToAction(nameof(PatientIndex));
                }

                return View(model);
            //}
           // TempData["error"] = "Error encountered.";
            return View(model);
        }
    }
}

Pathology.Web/Controllers/TestController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Pathology.Web.Models;
using Pathology.Web.Service.IService;

namespace Pathology.Web.Controllers
{
    public class TestController : Controller
    {
        private readonly ITestService _testService;
        public TestController(ITestService testService)
        {
            _testService = testService;
        }


        public async Task<IActionResult> TestIndex()
        {
            List<TestDto>? list = new();

            ResponseDto? response = await _testService.GetAllTestAsync();

            if (response != null && response.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<TestDto>>(Convert.ToString(response.Result));
            }

            return View(list);
        }

        public async Task<IActionResult> TestCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> TestCreate(TestDto model)
        {
            if (ModelState.IsValid)
            {
                ResponseDto? response = await _testService.CreateTestAsync(model);

                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Test created successfully";
                    return RedirectToAction(nameof(TestIndex));
                }
                else
                {
                    TempData["error"] = response?.Message;
                }
            }
            return View(model);
        }
        public async Task<IActionResult> TestDelete(int testId)
        {
            ResponseDto? response = await _testService.GetTestByIdAsync(testId);

            if (response != null && response.IsSuccess)
            {
                TestDto? model = JsonConvert.DeserializeObject<TestDto>(Convert.ToString(response.Result));
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> TestDelete(TestDto testDto)
        {
            ResponseDto? response = await _testService.DeleteTestAsync(testDto.TestId);

            if (response != null && response.IsSuccess)
            {

                return RedirectToAction(nameof(TestIndex));
            }

            return View(testDto);
        }

        public async Task<IActionResult> TestUpdate(int testId)
        {
            ResponseDto? response = await _testService.GetTestByIdAsync(testId);

            if (response != null && response.IsSuccess)
            {
                TestDto? model = JsonConvert.DeserializeObject<TestDto>(Convert.ToString(response.Result));
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> TestUpdate(TestDto testDto)
        {
            ResponseDto? response = await _testService.UpdateTestAsync(testDto);

            if (response != null && response.IsSuccess)
            {

                return RedirectToAction(nameof(TestIndex));
            }

            return View(testDto);
        }
    }
}

Pathology.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pathology.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pathology.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pathology.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Patient Management
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-controller="Patient" asp-action="PatientIndex">Patient</a></li>
                                <li><a class="dropdown-item" asp-controller="Test" asp-action="TestIndex">Test</a></li>

                                <li><hr class="dropdown-divider"></li>

                            </ul>
                            
                        </li>

                    </ul>
                    <ul class="navbar-nav">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link " href="#">Hello @User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted">
        <div class="text-center">
           Made By Prabath
            <i class="bi bi-prescription2"></i>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>